### ISSUE TITLE
UML de stare

### ISSUE THREAD

**Issue by ana285** [ana285/TIP#11]

**Comment by CatalinCata** [comment]
![untitled diagram 2 1 1](https://user-images.githubusercontent.com/37239413/37284402-15753dba-2604-11e8-92dc-4ea570001479.jpg)

**Comment by CatalinCata** [comment]
![untitled diagram 2 1 2](https://user-images.githubusercontent.com/37239413/37284511-7586dd26-2604-11e8-986e-611b2597e6aa.jpg)

**Comment by CatalinCata** [comment]
![untitled diagram 2 1 1 5](https://user-images.githubusercontent.com/37239413/37473224-95642396-2876-11e8-9fe6-b5c39a827303.jpg)
Am adaugat modul de a ajunge sa realizeze clientul lucrurile, prin apasarea unor butoane specifice...
