### ISSUE TITLE
Referirea și descrierea în text a fiecărei figuri/diagrame

### ISSUE THREAD

**Issue by ana285** [ana285/TIP#13]

**Comment by StefanaTiba** [comment]
Use Case si Information Flow
[Referirea.i.descrierea.in.text.a.fiecarei.figuri.docx](https://github.com/ana285/TIP/files/1818010/Referirea.i.descrierea.in.text.a.fiecarei.figuri.docx)

**Comment by Sabina085** [comment]
[DescriereUML_10_11.docx](https://github.com/ana285/TIP/files/1815116/DescriereUML_10_11.docx)
