### ISSUE TITLE
UML de information flow

### ISSUE THREAD

**Issue by ana285** [ana285/TIP#7]

**Comment by StefanaTiba** [comment]
![informationflowdiagram 2](https://user-images.githubusercontent.com/37262211/37308444-c0490414-2646-11e8-8e23-d22199d7468e.jpg)

**Comment by StefanaTiba** [comment]
![informationflowdiagram 3](https://user-images.githubusercontent.com/37262211/37505144-d8caeeb0-28eb-11e8-9dfc-8c28b05d5d6f.jpg)
